# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gbVkontakte' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gbVkontakte
  pod 'Alamofire', ‘~> 4.8.1’
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

end
